import { EnterpriseConfig } from './types';
import { Ai } from '../packages/modules/ai/src/index';
import { Storage } from '../packages/modules/storage/src/index';
import { UIManager } from '../packages/modules/ui/src/index';
import { AuthManager } from '../packages/modules/auth/src/index';
import { ProjectManager } from '../packages/modules/project/src/index';
import { SDK } from '../packages/modules/sdk/src/index';
export declare class EnterpriseSDK {
    private loader;
    private config;
    private isInitialized;
    constructor(userConfig?: Partial<EnterpriseConfig>);
    initialize(): Promise<void>;
    get ai(): import("./types").ModuleInterface;
    get storage(): import("./types").ModuleInterface;
    get ui(): import("./types").ModuleInterface;
    get project(): import("./types").ModuleInterface;
    get auth(): import("./types").ModuleInterface;
    get sdk(): import("./types").ModuleInterface;
    get runtime(): import("./core/runtime").WasmRuntime;
    get framework(): import("./types").FrameworkType;
    get nextjs(): Promise<any>;
    getConfig(): EnterpriseConfig;
    updateConfig(updates: Partial<EnterpriseConfig>): void;
    destroy(): Promise<void>;
    private ensureInitialized;
}
export declare function createEnterprise(config?: Partial<EnterpriseConfig>): Promise<EnterpriseSDK>;
declare const Enterprise: EnterpriseSDK;
export { Enterprise };
export { Ai, Storage, UIManager, AuthManager, ProjectManager, SDK };
export type { AIEnhanceOptions, AIGenerateOptions, AIAnalyzeOptions, AIEnhanceResult, AIGenerateResult, AIAnalyzeResult, } from '../packages/modules/ai/src/index';
export type { StorageSaveOptions, StorageLoadOptions, StorageFileInfo, } from '../packages/modules/storage/src/index';
export type { UIComponent, Theme } from '../packages/modules/ui/src/index';
export type { AuthConfig, User } from '../packages/modules/auth/src/index';
export type { Project, Task } from '../packages/modules/project/src/index';
export type { SDKMetaInfo, SDKSelfReferenceOptions } from '../packages/modules/sdk/src/index';
export * from './types';
export * from './hooks';
export declare const getNextjsBridge: () => Promise<any>;
export default Enterprise;
//# sourceMappingURL=index.d.ts.map